---
version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    ports: [27017:27017]
    volumes: [courier:/data/db]
  api:
    build:
      context: .
    container_name: courier_api
    restart: always
    ports: [4000:4000]
    volumes:
      - ./:/api/v1
      - ./package.json:/api/v1/package.json
      - /api/v1/node_modules
    environment:
      PORT: 4000
      NODE_ENV: development
      MONGODB_URL: mongodb://mongo:27017/
      JWT_SECRET: V1StGXR8_Z5jdHi6B-myT
      JWT_TOKENLIFE: 7d
    depends_on: [mongo]
volumes:
  courier:
